services:
  - type: web
    name: smartinvoice-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: "gunicorn server.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: B8q9kcewngMh1BaO_adExSOrplP69V1dfXWvKsYTfsjjFYwyghZKn0aPxgaL0ThbJqY
      - key: DJANGO_ALLOWED_HOSTS
        value: smartinvoice-backend.onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: smartinvoice-db
          property: connectionString
        
databases:
  - name: smartinvoice-db
    plan: free
# postgresql://smartuser:lvKNXvgkLsGvuZHVjnFwS3BQS3NSlReB@dpg-d19c2ljuibrs73c3eqd0-a/smartinvoice_db